name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  IMAGE_TAG: ${{ github.sha }}
  REPOSITORY: ${"ghcr.io/"${GITHUB_REPOSITORY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
      
        echo $IMAGE_TAG
        echo $REPOSITORY

        docker build . --file Dockerfile --tag $REPOSITORY:$IMAGE_TAG
    #     docker push ghcr.io/dogstailfarmer/exchanges-wrapper:latest
    #     docker push ghcr.io/dogstailfarmer/exchanges-wrapper:latest
